'use client';

import { useState, useRef, useCallback } from 'react';
import Spinner from './Spinner';

interface GeneratedTemplate {
  name: string;
  content: string;
  formatting?: { start: number; end: number; bold?: boolean; underline?: boolean }[];
}

interface AutoGenerateDialogProps {
  open: boolean;
  onClose: () => void;
  apiFetch: (url: string, options?: RequestInit) => Promise<Response>;
  onSaveTemplate: (tpl: GeneratedTemplate) => Promise<void>;
}

export default function AutoGenerateDialog({
  open,
  onClose,
  apiFetch,
  onSaveTemplate,
}: AutoGenerateDialogProps) {
  const [files, setFiles] = useState<File[]>([]);
  const [generating, setGenerating] = useState(false);
  const [generatedTemplates, setGeneratedTemplates] = useState<GeneratedTemplate[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [savingId, setSavingId] = useState<number | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleFileChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const selected = Array.from(e.target.files || []);
    setFiles((prev) => {
      const combined = [...prev, ...selected];
      return combined.slice(0, 3);
    });
    // Reset input damit gleiche Datei erneut ausgewählt werden kann
    e.target.value = '';
  }, []);

  const removeFile = useCallback((index: number) => {
    setFiles((prev) => prev.filter((_, i) => i !== index));
  }, []);

  const handleGenerate = useCallback(async () => {
    if (files.length === 0) return;
    setGenerating(true);
    setError(null);
    setGeneratedTemplates([]);

    try {
      const formData = new FormData();
      for (const file of files) {
        formData.append('files', file);
      }

      const res = await apiFetch('/api/templates/auto-generate', {
        method: 'POST',
        body: formData,
      });
      const data = await res.json();

      if (!data.success) {
        setError(data.error || 'Fehler bei der Generierung');
        return;
      }

      if (!data.templates || data.templates.length === 0) {
        setError('Keine Bausteine erkannt. Möglicherweise sind die Dokumente nicht geeignet.');
        return;
      }

      setGeneratedTemplates(data.templates);
    } catch (err: any) {
      setError(err.message || 'Netzwerkfehler');
    } finally {
      setGenerating(false);
    }
  }, [files, apiFetch]);

  const handleSave = useCallback(async (tpl: GeneratedTemplate, index: number) => {
    setSavingId(index);
    try {
      await onSaveTemplate(tpl);
      setGeneratedTemplates((prev) => prev.filter((_, i) => i !== index));
    } catch {
      setError('Fehler beim Speichern');
    } finally {
      setSavingId(null);
    }
  }, [onSaveTemplate]);

  const handleSaveAll = useCallback(async () => {
    for (let i = generatedTemplates.length - 1; i >= 0; i--) {
      await handleSave(generatedTemplates[i], i);
    }
  }, [generatedTemplates, handleSave]);

  if (!open) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-start justify-center pt-[8vh] bg-black/40 px-4" onClick={onClose}>
      <div
        className="w-full max-w-2xl rounded-xl border border-gray-200 bg-white shadow-2xl dark:border-gray-700 dark:bg-gray-900 max-h-[80vh] flex flex-col"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-4 py-3 border-b border-gray-200 dark:border-gray-700 shrink-0">
          <h2 className="text-sm font-semibold text-gray-900 dark:text-gray-100">
            Bausteine automatisch erzeugen
          </h2>
          <button onClick={onClose} className="text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 text-lg leading-none">✕</button>
        </div>

        <div className="flex-1 overflow-y-auto px-4 py-3 space-y-4">
          {error && (
            <div className="text-xs text-red-600 dark:text-red-400 bg-red-50 dark:bg-red-900/20 px-3 py-2 rounded">
              {error}
              <button onClick={() => setError(null)} className="ml-2 font-bold">✕</button>
            </div>
          )}

          {/* File Upload */}
          {generatedTemplates.length === 0 && (
            <div className="space-y-3">
              <p className="text-xs text-gray-500 dark:text-gray-400">
                Lade bis zu 3 bestehende Dokumente (PDF oder DOCX) hoch. Der KI-Agent extrahiert daraus
                Textbausteine, entfernt personenbezogene Daten, markiert Platzhalter mit [eckigen Klammern]
                und schlägt Titel vor.
              </p>

              {/* File List */}
              {files.length > 0 && (
                <div className="space-y-1">
                  {files.map((file, i) => (
                    <div key={i} className="flex items-center justify-between px-2 py-1.5 bg-gray-50 dark:bg-gray-800 rounded text-xs">
                      <span className="truncate text-gray-700 dark:text-gray-300">{file.name}</span>
                      <button
                        onClick={() => removeFile(i)}
                        className="text-gray-400 hover:text-red-500 shrink-0 ml-2"
                      >
                        ×
                      </button>
                    </div>
                  ))}
                </div>
              )}

              <div className="flex items-center gap-2">
                <input
                  ref={fileInputRef}
                  type="file"
                  accept=".pdf,.docx,.doc"
                  multiple
                  onChange={handleFileChange}
                  className="hidden"
                />
                <button
                  onClick={() => fileInputRef.current?.click()}
                  disabled={files.length >= 3}
                  className="text-xs px-3 py-1.5 rounded border border-gray-300 dark:border-gray-600 text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-800 disabled:opacity-40"
                >
                  + Datei auswählen
                </button>
                <span className="text-[10px] text-gray-400">{files.length}/3 Dateien</span>
                {files.length > 0 && (
                  <button
                    onClick={() => setFiles([])}
                    className="text-[10px] text-gray-400 hover:text-red-500"
                  >
                    Alle entfernen
                  </button>
                )}
              </div>

              <button
                onClick={handleGenerate}
                disabled={files.length === 0 || generating}
                className="w-full px-3 py-2 text-sm bg-blue-500 text-white rounded hover:bg-blue-600 disabled:opacity-50 flex items-center justify-center gap-2"
              >
                {generating ? (
                  <><Spinner size={14} /> Generiere Bausteine...</>
                ) : (
                  '🚀 Bausteine generieren'
                )}
              </button>
            </div>
          )}

          {/* Generated Templates */}
          {generatedTemplates.length > 0 && (
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <p className="text-xs text-gray-500">
                  {generatedTemplates.length} Baustein{generatedTemplates.length !== 1 ? 'e' : ''} erkannt:
                </p>
                <button
                  onClick={handleSaveAll}
                  className="text-xs px-2.5 py-1 rounded bg-emerald-100 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-300 hover:bg-emerald-200 dark:hover:bg-emerald-800/40"
                >
                  Alle speichern ({generatedTemplates.length})
                </button>
              </div>

              {generatedTemplates.map((tpl, index) => (
                <div key={index} className="border border-gray-200 dark:border-gray-700 rounded-lg overflow-hidden">
                  {/* Header */}
                  <div className="flex items-center justify-between px-3 py-2 bg-gray-50 dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700">
                    <div className="flex items-center gap-2 min-w-0 flex-1">
                      <span className="text-xs font-medium text-gray-800 dark:text-gray-200 truncate">
                        {tpl.name || `Baustein ${index + 1}`}
                      </span>
                      <span className="text-[10px] text-gray-400 shrink-0">{tpl.content.length} Zeichen</span>
                    </div>
                    <button
                      onClick={() => handleSave(tpl, index)}
                      disabled={savingId === index}
                      className="text-[10px] px-2 py-0.5 rounded bg-emerald-100 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-300 hover:bg-emerald-200 dark:hover:bg-emerald-800/40 shrink-0 ml-2"
                    >
                      {savingId === index ? '...' : '📋 Speichern'}
                    </button>
                  </div>

                  {/* Content Preview */}
                  <div className="px-3 py-2 max-h-48 overflow-y-auto">
                    <pre className="text-[11px] text-gray-700 dark:text-gray-300 font-mono whitespace-pre-wrap leading-relaxed">
                      {tpl.content}
                    </pre>
                  </div>

                  {/* Formatting info */}
                  {tpl.formatting && tpl.formatting.length > 0 && (
                    <div className="px-3 py-1 border-t border-gray-100 dark:border-gray-800 text-[9px] text-gray-400">
                      Formatierung: {tpl.formatting.length} Markierung{ tpl.formatting.length !== 1 ? 'en' : ''}
                    </div>
                  )}
                </div>
              ))}

              <button
                onClick={() => { setGeneratedTemplates([]); setFiles([]); }}
                className="w-full text-xs text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 py-1"
              >
                Neue Dokumente analysieren
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
